<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Billiepayment\BilliePaymentMethod\Block\Info\Payafterdelivery $block
 */
$specificInfo = $block->getSpecificInformation();
?>
<?= $block->escapeHtml($block->getMethod()->getTitle()) ?>
<?php if ($block->isShipped()): ?>
<div>
    <?= /* @noEscape */ __('Bitte überweisen Sie den Rechnungsbetrag bis zum %1 unter Angabe des Rechnungsnummer auf folgendes Konto:', $block->getDuration()) ?>
</div>
<?php endif ?>
<?php if ($specificInfo): ?>
    <table class="data-table admin__table-secondary">
        <?php foreach ($specificInfo as $label => $value): ?>
            <tr>
                <th><?= $block->escapeHtml($label) ?>:</th>
                <td>
                    <?= /* @noEscape */ nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true)))) ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif;?>
<?php if ($block->isShipped()): ?>
    <?= /* @noEscape */ __('Bitte beachten Sie, dass Ihre Rechnung nur dann beglichen ist, wenn Ihre Zahlung auf das oben genannte Konto erfolgt.') ?>
<?php endif ?>
<?= $block->getChildHtml() ?>
